services:
  jupyterlab:
    build: 
      context: .
      dockerfile: Python312file
    volumes:
      - type: bind
        source: /path/to/project_name
        target: /app/project_name
    ports:
      - "8888:8888"
      - "54321:54321"

networks:
  podman:
    external: true
